-- return {
-- 	"cordx56/rustowl",
-- 	build = "cd rustowl && cargo install --path . --locked",
-- 	lazy = false, -- This plugin is already lazy
-- 	opts = {
-- 		client = {
-- 			on_attach = function(_, buffer)
-- 				vim.keymap.set("n", "<leader>l", function()
-- 					require("rustowl").toggle(buffer)
-- 				end, { buffer = buffer, desc = "Toggle RustOwl" })
-- 			end,
-- 		},
-- 	},
-- }
return {}
